version: "3.8"
services:
  alloy:
    image: grafana/alloy:latest
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
    command: ["run", "/etc/alloy/config.alloy"]
    ports:
      - "4317:4317"
      - "4318:4318"
      - "9464:9464"

  cortex_tenant:
    image: ghcr.io/blind-oracle/cortex-tenant:latest
    ports:
      - "8085:8085" # Remote write will go here
    volumes:
      - ./cortex-tenant.yaml:/etc/cortex-tenant.yaml
    command: ["-config", "/etc/cortex-tenant.yaml"]

  mimir:
    image: grafana/mimir:latest
    ports:
      - "9009:9009"
    command: ["-config.file=/etc/mimir/mimir.yaml"]
    volumes:
      - ./mimir-data:/tmp/mimir
      - ./mimir.yaml:/etc/mimir/mimir.yaml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
